# Dataset Inspection

Use this notebook to inspect the TriviaQA schema, confirm field names, and identify what should flow into preprocessing.

In [7]:
from pathlib import Path
import sys

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

sys.executable

'c:\\Users\\tanis\\OneDrive\\Desktop\\LLM_factcheck\\LLM_factcheck\\.venv\\Scripts\\python.exe'

In [8]:
import pandas as pd

from src.data.loader import extract_triviaqa_aliases, load_hf_dataset

In [9]:
dataset = load_hf_dataset("trivia_qa", "rc")
dataset

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

c:\Users\tanis\OneDrive\Desktop\LLM_factcheck\LLM_factcheck\.venv\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\tanis\.cache\huggingface\hub\datasets--trivia_qa. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/26 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/26 [00:00<?, ?files/s]

rc/train-00000-of-00026.parquet:   0%|          | 0.00/308M [00:00<?, ?B/s]

rc/train-00001-of-00026.parquet:   0%|          | 0.00/298M [00:00<?, ?B/s]

rc/train-00002-of-00026.parquet:   0%|          | 0.00/290M [00:00<?, ?B/s]

rc/train-00003-of-00026.parquet:   0%|          | 0.00/444M [00:00<?, ?B/s]

rc/train-00004-of-00026.parquet:   0%|          | 0.00/461M [00:00<?, ?B/s]

rc/train-00005-of-00026.parquet:   0%|          | 0.00/474M [00:00<?, ?B/s]

rc/train-00006-of-00026.parquet:   0%|          | 0.00/404M [00:00<?, ?B/s]

rc/train-00007-of-00026.parquet:   0%|          | 0.00/324M [00:00<?, ?B/s]

rc/train-00008-of-00026.parquet:   0%|          | 0.00/329M [00:00<?, ?B/s]

rc/train-00009-of-00026.parquet:   0%|          | 0.00/336M [00:00<?, ?B/s]

rc/train-00010-of-00026.parquet:   0%|          | 0.00/400M [00:00<?, ?B/s]

rc/train-00011-of-00026.parquet:   0%|          | 0.00/370M [00:00<?, ?B/s]

rc/train-00012-of-00026.parquet:   0%|          | 0.00/341M [00:00<?, ?B/s]

rc/train-00013-of-00026.parquet:   0%|          | 0.00/327M [00:00<?, ?B/s]

rc/train-00014-of-00026.parquet:   0%|          | 0.00/310M [00:00<?, ?B/s]

rc/train-00015-of-00026.parquet:   0%|          | 0.00/157M [00:00<?, ?B/s]

rc/train-00016-of-00026.parquet:   0%|          | 0.00/136M [00:00<?, ?B/s]

rc/train-00017-of-00026.parquet:   0%|          | 0.00/159M [00:00<?, ?B/s]

rc/train-00018-of-00026.parquet:   0%|          | 0.00/200M [00:00<?, ?B/s]

rc/train-00019-of-00026.parquet:   0%|          | 0.00/180M [00:00<?, ?B/s]

rc/train-00020-of-00026.parquet:   0%|          | 0.00/150M [00:00<?, ?B/s]

rc/train-00021-of-00026.parquet:   0%|          | 0.00/153M [00:00<?, ?B/s]

rc/train-00022-of-00026.parquet:   0%|          | 0.00/147M [00:00<?, ?B/s]

rc/train-00023-of-00026.parquet:   0%|          | 0.00/157M [00:00<?, ?B/s]

rc/train-00024-of-00026.parquet:   0%|          | 0.00/154M [00:00<?, ?B/s]

rc/train-00025-of-00026.parquet:   0%|          | 0.00/158M [00:00<?, ?B/s]

rc/validation-00000-of-00004.parquet:   0%|          | 0.00/327M [00:00<?, ?B/s]

rc/validation-00001-of-00004.parquet:   0%|          | 0.00/296M [00:00<?, ?B/s]

rc/validation-00002-of-00004.parquet:   0%|          | 0.00/184M [00:00<?, ?B/s]

rc/validation-00003-of-00004.parquet:   0%|          | 0.00/129M [00:00<?, ?B/s]

rc/test-00000-of-00004.parquet:   0%|          | 0.00/307M [00:00<?, ?B/s]

rc/test-00001-of-00004.parquet:   0%|          | 0.00/288M [00:00<?, ?B/s]

rc/test-00002-of-00004.parquet:   0%|          | 0.00/171M [00:00<?, ?B/s]

rc/test-00003-of-00004.parquet:   0%|          | 0.00/128M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/138384 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/17944 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/17210 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/24 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['question', 'question_id', 'question_source', 'entity_pages', 'search_results', 'answer'],
        num_rows: 138384
    })
    validation: Dataset({
        features: ['question', 'question_id', 'question_source', 'entity_pages', 'search_results', 'answer'],
        num_rows: 17944
    })
    test: Dataset({
        features: ['question', 'question_id', 'question_source', 'entity_pages', 'search_results', 'answer'],
        num_rows: 17210
    })
})

In [10]:
train_df = pd.DataFrame(dataset["train"])
train_df.head()

,question,question_id,question_source,entity_pages,search_results,answer
0,Which American-born Sinclair won the Nobel Pri...,tc_1,http://www.triviacountry.com/,"{'doc_source': [], 'filename': [], 'title': []...",{'description': ['The Nobel Prize in Literatur...,"{'aliases': ['(Harry) Sinclair Lewis', 'Harry ..."
1,Where in England was Dame Judi Dench born?,tc_3,http://www.triviacountry.com/,"{'doc_source': ['TagMe', 'TagMe'], 'filename':...","{'description': ['Judi Dench, Actress: Skyfall...","{'aliases': ['Park Grove (1895)', 'York UA', '..."
2,In which decade did Billboard magazine first p...,tc_5,http://www.triviacountry.com/,"{'doc_source': [], 'filename': [], 'title': []...",{'description': ['Song chart US Billboard. The...,"{'aliases': ['30's', '30’s', '30s', '30s AD', ..."
3,From which country did Angola achieve independ...,tc_8,http://www.triviacountry.com/,"{'doc_source': ['TagMe', 'TagMe', 'Search'], '...",{'description': ['Angola; Angola from past to ...,"{'aliases': ['Portogało', 'Republic of Portuga..."
4,Which city does David Soul come from?,tc_9,http://www.triviacountry.com/,"{'doc_source': ['TagMe'], 'filename': ['David_...","{'description': ['David Soul, Actor: Starsky a...","{'aliases': ['Chi-Beria', 'Sayre language acad..."

In [11]:
train_df.columns.tolist()

['question',
 'question_id',
 'question_source',
 'entity_pages',
 'search_results',
 'answer']

In [12]:
sample_rows = train_df.sample(5, random_state=42).copy()
sample_rows["answer_aliases"] = sample_rows["answer"].apply(extract_triviaqa_aliases)
sample_rows[["question", "answer_aliases"]]

,question,answer_aliases
101480,"""What fictional ship, with black hull and sail...","[Black Pearl, black pearl, Wicked Wench]"
100105,Which British TV series about cars that began ...,"[Top Gear, top gear, Top Gear UK, Top Gear (di..."
94815,Name Captain Flint's quartermaster in the nove...,"[Long John Silver, long john silver]"
96476,What Christmas-time song did James Pierpont co...,"[Jingle Bells, jingle bells, Jingle Bells, Jin..."
56189,"Established in April 1951, which was the first...","[Peak District, peak district, Peak District N..."

In [13]:
first_row = dataset["train"][0]
{
    "question": first_row.get("question"),
    "answer_keys": list(first_row.get("answer", {}).keys()),
    "search_results_keys": list(first_row.get("search_results", {}).keys()) if isinstance(first_row.get("search_results"), dict) else type(first_row.get("search_results")).__name__,
}

{'question': 'Which American-born Sinclair won the Nobel Prize for Literature in 1930?',
 'answer_keys': ['aliases',
  'normalized_aliases',
  'matched_wiki_entity_name',
  'normalized_matched_wiki_entity_name',
  'normalized_value',
  'type',
  'value'],
 'search_results_keys': ['description',
  'filename',
  'rank',
  'title',
  'url',
  'search_context']}

## Notes

- Which field contains the question?
- Which field contains the gold answer and aliases?
- Is retrieval evidence in `search_results` or another field?
- Which nested fields need flattening before benchmark export?
- Are there rows that should be filtered before evaluation?